from typing import Final

DEFAULT_VALUE_POMODORO_TIMER: Final = 25.00
DEFAULT_VALUE_SHORT_BREAK_TIMER: Final = 5.00
DEFAULT_VALUE_LONG_BREAK_TIMER: Final = 15.00

DEFAULT_VALUE_POMODORO_TIMER_STR: Final = f"{DEFAULT_VALUE_POMODORO_TIMER:.2f}".replace(".", ":")
DEFAULT_VALUE_SHORT_BREAK_TIMER_STR: Final = f"{DEFAULT_VALUE_SHORT_BREAK_TIMER:.2f}".replace(".", ":")
DEFAULT_VALUE_LONG_BREAK_TIMER_STR: Final = f"{DEFAULT_VALUE_LONG_BREAK_TIMER:.2f}".replace(".", ":")